CC=gcc
CFLAGS=-Wall

pingpong-os: queue.c pingpong.c pingpong-tasks1.c pingpong-tasks2.c pingpong-tasks3.c
	$(CC) -o pingpong-os1 queue.c pingpong.c pingpong-tasks1.c
	$(CC) -o pingpong-os2 queue.c pingpong.c pingpong-tasks2.c
	$(CC) -o pingpong-os3 queue.c pingpong.c pingpong-tasks3.c
