CC=gcc
CFLAGS=-Wall

pingpong-os: queue.c pingpong.c pingpong-contab.c pingpong-contab-prio.c
	$(CC) -Wall -o pingpong-os1 queue.c pingpong.c pingpong-contab.c
	$(CC) -Wall -o pingpong-os2 queue.c pingpong.c pingpong-contab-prio.c

